# Generated by Django 3.2.9 on 2021-11-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranobe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranobe',
            name='year',
        ),
    ]
